# 文件名: .github/workflows/sync.yml
name: Sync Fork with Merge Strategy

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 步骤 1: 使用 PAT checkout 你的仓库，以便拥有推送权限
      - name: Checkout Fork
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SYNC_TOKEN }}
          # 拉取所有 git 历史，以便合并
          fetch-depth: 0

      # 步骤 2: 添加源仓库 (upstream)
      - name: Set up upstream remote
        run: git remote add upstream https://github.com/bia-pain-bache/BPB-Worker-Panel.git

      # 步骤 3: 从源仓库拉取最新代码
      - name: Fetch from upstream
        run: git fetch upstream

      # 步骤 4: 合并更新 (最关键的区别)
      - name: Merge upstream changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout main
          # 将 upstream/main 合并到你的 main
          # 这会保留你的 workflow 文件，同时拉取所有更新
          git merge upstream/main

      # 步骤 5: 将更新推送到你的 Fork 仓库
      - name: Push changes to fork
        # 这里不需要 --force
        run: git push origin main
